version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd backend
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - npm run build
  post_build:
    commands:
      - echo "Preparing for deployment..."
      - cd ..
      - zip -r backend-deploy.zip backend/* backend/.[^.]*
      - echo "Uploading to S3..."
      - aws s3 cp backend-deploy.zip s3://open-mic-guru/backend-deploy.zip
      - export VERSION_LABEL=v-$(date +%Y-%m-%d-%H-%M-%S)
      - echo "Creating Elastic Beanstalk application version: $VERSION_LABEL"
      - |
        aws elasticbeanstalk create-application-version \
          --application-name open-mic-guru \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=open-mic-guru,S3Key=backend-deploy.zip
      - |
        aws elasticbeanstalk update-environment \
          --environment-name open-mic-guru-backend-env \
          --version-label $VERSION_LABEL
artifacts:
  files:
    - backend-deploy.zip
  base-directory: .