name: Run Tests for Frontend and Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --coverage

      - name: Upload coverage report (frontend)
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/coverage

  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run tests
        working-directory: ./backend
        run: npm test -- --coverage

      - name: Upload coverage report (backend)
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage

  collect-coverage:
    name: Collect Coverage
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download frontend coverage
        uses: actions/download-artifact@v3
        with:
          name: frontend-coverage
          path: coverage/frontend

      - name: Download backend coverage
        uses: actions/download-artifact@v3
        with:
          name: backend-coverage
          path: coverage/backend

      - name: Upload combined coverage
        uses: actions/upload-artifact@v3
        with:
          name: combined-coverage
          path: coverage